---
- name: Execute deploy in Kubernetes Cluster
  hosts: local
  gather_facts: no
  tasks:
  - name: Create klever Namespace
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
            name: klever
  - name: Create deployment in kubernetes cluster
    k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: klever
          labels:
            app: appidadeklv
          name: appidadeklv
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: appidadeklv
          template:
            metadata:
              labels:
                app: appidadeklv
            spec:
              containers:
              - image: rfabricio/appidadeklv:latest
                name: appidadeklv
                ports:
                - containerPort: 5000
                livenessProbe:
                  httpGet:
                    path: /health
                    port: 5000
                  initialDelaySeconds: 3
                  periodSeconds: 2
                  timeoutSeconds: 1
                  successThreshold: 1
                  failureThreshold: 2
                readinessProbe:
                  httpGet:
                    path: /ready
                    port: 5000
                  initialDelaySeconds: 3
                  periodSeconds: 2
                  timeoutSeconds: 1
                  successThreshold: 1
                  failureThreshold: 2          
                resources: {}
        status: {}
  - name: Create service in kubernetes cluster
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          namespace: klever
          labels:
            app: appidadeklv
          name: appidadeklv
        spec:
          ports:
          - port: 80
            protocol: TCP
            targetPort: 5000
            nodePort: 30000
          selector:
            app: appidadeklv
          type: LoadBalancer
        status:
          loadBalancer: {}