apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  template:
    spec:
      containers:
        - name: sampleapp
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 30m
              memory: 64Mi