apiVersion: v1
kind: Service
metadata:
  namespace: klever
  labels:
    app: appidadeklv
  name: appidadeklv
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 30000
  selector:
    app: appidadeklv
  type: LoadBalancer
status:
  loadBalancer: {}